[project]
name = "myi10tele"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ffmpeg>=1.4",
    "gym-aloha>=0.1.3",
    "glfw",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "lerobot",
    "matplotlib",
    "mujoco",
    "numpy",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.2",
    "pillow",
    "pip>=26.1.1",
    "plotly",
    "pyautogui",
    "scipy",
    "termcolor>=3.3.0",
    "torch",
    "torchcodec>=0.10.0",
    "transformers @ git+https://github.com/huggingface/transformers.git@dcddb970176382c0fcf4521b0c0e6fc15894dfe0",
    "trimesh",
]
